deviceSettings:
    id: f560704a-e8a3-4e92-ac2f-c1c49b263a2c
    type: Pulse

connectionSettings:
    serverHost: "http://localhost:8080"
    connTimeout: 20
    maxIdleConns: 10
    idleConnTimeout: 30
    disableCompression: true
